### ISSUE TITLE
No query type 'lint' defined

### ISSUE THREAD

**Issue by tststs** [angelozerr/tern-lint#64]
Hey,

with every request to the server, i get this error message.
Do i miss something?

.tern-project:
```
{
  "ecmaVersion": 6,
  "libs": [
    "browser"
  ],
  "loadEagerly": [
    "app/js/**/*.js"
  ],
  "plugins": {
    "complete_strings": {},
    "es_modules": {},
    "lint": {
      "config": {}
    },
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

post:
```
  lint: (file, text) ->
    @post(JSON.stringify
      query:
        type: 'lint'
        file: file,
        files: [
          type: 'full'
          name: file
          text: text
        ]
    )
```

Thanks and greetings,
tststs
